[package]
name = "image_processing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4"
cgmath = "0.18.0"
png = "0.18.0-rc"
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = "25.0.2"
pretty_env_logger = "0.5.0"
thiserror = "2.0.12"
winit = "0.30.11"

